### ISSUE TITLE
Get estimation of number of hospitalized from pdf

### ISSUE THREAD

**Issue by KPunktRPunkt** [DLR-SC/memilio#110] opened 2021-10-25 12:19 UTC
We want to have the numbers of hospitalized. There are different possibilities to get it:

- [ ] from RKI Tagesbericht pdf 
- [ ] from monthly-data of RKI. Until lately it was a xlsx file now it seems to be on github as well: https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland

**Comment by mknaranja** [comment] 2021-12-14 07:56
Data is now also available at https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland

**Comment by dabele** [comment] 2022-06-27 15:03
Duplicate of #128

**Closed by dabele** 2022-06-27 15:03 UTC
Labels: loc::data handling
