### ISSUE TITLE
Information links in README.rst broken

### ISSUE THREAD

**Issue by udiallo** [DLR-SC/memilio#141] opened 2021-12-06 14:37 UTC
Under the point "Information" are three links (documentation, python coverage report and pylint report) provided but broken (leads to old Gitlab.dlr page).

Is it possible to provide the updated links to the documentations?

Thanks in advance.

**Comment by dabele** [comment] 2021-12-07 08:47
coverage: https://app.codecov.io/gh/DLR-SC/memilio
documentation: https://dlr-sc.github.io/memilio/documentation/index.html
pylint is not currently published as far as I can tell.
These links are also in the main readme.

closing this issue, duplicate of #112.

**Closed by dabele** 2021-12-07 08:47 UTC
